version: "3"
services:
  www:
    build: 
      context: .
      dockerfile: Dockerfile
    image: php:apache 
    volumes:
      - "./:/var/www/html"
    ports:
      - 7000:80
      - 443:443
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
